# دیتای ثابت بازی — از فایل «اطلاعات بازی»

REGIONS = {
    "north":  {"name": "شمال", "special": ["نگهبان شمال", "سوار زمستان"],
               "castles": ["وینترفل","دردفورت","بارولندز","کارهولد","لاست‌هرت","تورنز اسکوئر","دیپ‌وود موت","موات کیلین","قلعهٔ سروین","تال‌هارت","فلینت"],
               "ports": ["وایت هاربر","بارو‌تاون","بندر دیپ‌وود"]},
    "iron":   {"name": "جزایر آهن", "special": ["غارتگر آهن", "جنگجوی تبردار"],
               "castles": ["پایک","هارلاو هال","تن تاور","بلک‌تاید","اورکمونت","سالت‌کلیف"],
               "ports": ["لردپورت","بندر هارلاو"]},
    "river":  {"name": "ریورلندز", "special": ["پیادهٔ رودخانه", "کماندار باتلاق"],
               "castles": ["ریورران","هارنهال","دوقلوها","سیگارد","راونتری","استون‌هج","آکورن هال","دارری"],
               "ports": ["میدن‌پول","سالت‌پنس"]},
    "west":   {"name": "وسترلندز", "special": ["پیادهٔ زره‌سنگین", "شوالیه لنیستری"],
               "castles": ["کسترلی راک","کریگ","کی‌هال","گلدن‌توث","فرکسل"],
               "ports": ["لنیسپورت"]},
    "reach":  {"name": "ریچ", "special": ["کماندار ریچ", "سوار زره‌دار ریچ"],
               "castles": ["های‌گاردن","هورن‌هیل","تارلی‌هال","بریج‌واتر","آشبروک","ردلیک","سان‌هوس"],
               "ports": ["اولدتاون","بیتربریج"]},
    "vale":   {"name": "درهٔ آرین", "special": ["نیزه‌دار کوهستان", "سوار دره"],
               "castles": ["ایری","گیتس آو د مون","ران‌استون","هارتز هوم","ردفورت","لانگ‌بو هال"],
               "ports": ["گال‌تاون"]},
    "storm":  {"name": "استورملندز", "special": ["جنگجوی طوفان", "سوار طوفان"],
               "castles": ["استورمز اند","گریفینز روست","تارث","رین‌هال","فل‌وود"],
               "ports": ["شیپ‌بریک بی"]},
    "dorne":  {"name": "دورن", "special": ["نیزه‌دار دورنی", "سوار شن"],
               "castles": ["سان‌اسپیر","واتر گاردنز","استارفال","یرونوود","اسکای‌ریچ","هل‌هولت"],
               "ports": ["پلنکی‌تاون","بندر استارفال"]},
    "crown":  {"name": "کراون‌لندز", "special": [],
               "castles": ["رد کیپ","دراگون‌استون","روزبی","استوک‌ورث","دارک‌لین هال"],
               "ports": ["کینگز لندینگ"]},
}

COMMON_TROOPS = {
    "infantry":  {"name": "پیاده‌نظام",       "cost": 2},
    "spearman":  {"name": "نیزه‌دار",          "cost": 1},
    "archer":    {"name": "کماندار",           "cost": 1},
    "light_cav": {"name": "سواره‌نظام سبک",   "cost": 2},
    "heavy_cav": {"name": "سواره‌نظام سنگین", "cost": 3},
}
SPECIAL_TROOP_COST = 4

BUILDINGS = {
    "gold_mine":   {"name": "معدن طلا",   "cost": {"gold": 400, "stone": 100}, "hours": 12, "cat": "production", "effect": {"gold_pct": 100}},
    "stone_mine":  {"name": "معدن سنگ",   "cost": {"gold": 150}, "hours": 4,  "cat": "production", "effect": {"stone_pct": 100}},
    "iron_mine":   {"name": "معدن آهن",   "cost": {"gold": 200}, "hours": 6,  "cat": "production", "effect": {"iron_pct": 100}},
    "market":      {"name": "بازار",       "cost": {"gold": 250}, "hours": 6, "cat": "production", "effect": {"gold_pct": 50}},
    "farm":        {"name": "مزرعه",       "cost": {"gold": 100}, "hours": 3, "cat": "production", "effect": {"food_pct": 100}},
    "ranch":       {"name": "دامداری",     "cost": {"gold": 150}, "hours": 4, "cat": "production", "effect": {"food_pct": 50}},
    "treasury":    {"name": "خزانه",       "cost": {"gold": 300, "stone": 150}, "hours": 8, "cat": "storage", "effect": {"gold_cap": 800}},
    "granary":     {"name": "انبار غله",   "cost": {"gold": 200, "stone": 50}, "hours": 5, "cat": "storage", "effect": {"food_cap": 500}},
    "warehouse":   {"name": "انبار",        "cost": {"gold": 200, "stone": 80}, "hours": 5, "cat": "storage", "effect": {"iron_cap": 200, "stone_cap": 200}},
    "camp_sword":  {"name": "کمپ شمشیرزن",       "cost": {"gold": 250, "iron": 50}, "hours": 6, "cat": "camp", "effect": {}},
    "camp_spear":  {"name": "کمپ نیزه‌داران",     "cost": {"gold": 200, "iron": 30}, "hours": 5, "cat": "camp", "effect": {}},
    "camp_archer": {"name": "کمپ کمانداران",      "cost": {"gold": 200, "iron": 20}, "hours": 5, "cat": "camp", "effect": {}},
    "camp_lcav":   {"name": "کمپ سوارهٔ سبک",    "cost": {"gold": 350, "iron": 60}, "hours": 8, "cat": "camp", "effect": {}},
    "camp_hcav":   {"name": "کمپ سوارهٔ سنگین",  "cost": {"gold": 500, "iron": 120}, "hours": 12, "cat": "camp", "effect": {}},
    "wall":        {"name": "دیوار دفاعی", "cost": {"gold": 400, "stone": 300}, "hours": 14, "cat": "defense", "effect": {}},
    "watchtower":  {"name": "برج نگهبانی", "cost": {"gold": 250, "stone": 120}, "hours": 7, "cat": "defense", "effect": {}},
    "port":        {"name": "بندر",         "cost": {"gold": 600, "stone": 200}, "hours": 16, "cat": "defense", "effect": {}},
}
