import { useEffect, useState } from 'react';
import { api } from '../api.js';

const STATUSES={awaiting_roleplay:'در انتظار رول',roleplay_submitted:'رول ارسال شده',expired:'مهلت گذشته',scheduled:'زمان‌بندی شده',funding:'سرمایه‌گذاری',active:'فعال',proposed:'پیشنهاد شده',accepted:'پذیرفته شده',alive:'زنده'};
const FIELDS = {due_at:'موعد خراج',expires_at:'انقضا',adult_at:'بلوغ',next_production:'تولید روزانهٔ بعدی',next_feast:'پایان کول‌داون ضیافت',next_daily_boundary:'مرز روز بازی و جایزه',deadline:'مهلت رول', arrival_at:'زمان رسیدن', publish_at:'انتشار', funding_deadline:'پایان سرمایه‌گذاری', next_payout_at:'پرداخت بعدی'};
export default function AdminTimeManagement({toast}) {
  const [workers,setWorkers]=useState(null),[data,setData]=useState(null),[rows,setRows]=useState(null),[kind,setKind]=useState('rebellions'),[page,setPage]=useState(1),[busy,setBusy]=useState(false),[zone,setZone]=useState('Asia/Tehran'),[day,setDay]=useState(1),[reason,setReason]=useState(''),[selected,setSelected]=useState(null),[minutes,setMinutes]=useState(1440);
  const load=async()=>{const d=await api.adminTimeOverview();setData(d);setWorkers(d.workers);setZone(d.timezone);setDay(d.calendar.day)};
  const timers=async()=>setRows(await api.adminTimeTimers(kind,page));
  useEffect(()=>{load().catch(e=>toast(e.message))},[]);
  useEffect(()=>{let active=true;setRows(null);api.adminTimeTimers(kind,page).then(r=>{if(active)setRows(r)}).catch(e=>toast(e.message));return()=>{active=false}},[kind,page]);
  const action=async(fn)=>{setBusy(true);try{await fn();await load();await timers();toast('تنظیم زمان ذخیره شد')}catch(e){toast(e.message)}finally{setBusy(false)}};
  const stamp=v=>v?new Date(v).toLocaleString('fa-IR',{timeZone:zone,hour12:false}):'نامشخص';
  if(!data)return <div className="loading">در حال دریافت ساعت‌های سرور…</div>;
  return <>
    <section className="card"><h3>زمان و تقویم سامانه</h3><p className="page-sub">اطلاعات ساعت در زمان دریافت ثبت شده است. ساعت داخلی پس از توقف از ساعت واقعی عقب می‌ماند؛ آن را به عنوان تاریخ شمسی تفسیر نکنید.</p><button className="btn ghost" disabled={busy} onClick={()=>action(async()=>{})}>تازه‌سازی</button>
      <p>ساعت واقعی: {stamp(data.real_now)}</p><p>زمان داخلی UTC: <span dir="ltr">{data.game_now}</span></p><p>اختلاف ساعت بازی و واقعی: {(data.offset_seconds/3600).toLocaleString('fa-IR',{maximumFractionDigits:2})} ساعت</p><p>وضعیت: {data.paused?'متوقف':'در حال اجرا'} {data.reason}</p><p>ذخیره‌سازی: UTC · تقویم نمایش: شمسی · منطقهٔ نمایش: {data.timezone}</p>
      {data.domains.map(x=><div className="control-sub" key={x.name}><b>{x.name}</b><p>{x.use}</p><small>{x.pause?'با توقف بازی می‌ایستد':'به توقف بازی وابسته نیست'}</small></div>)}
    </section>
    <section className="card"><h3>منطقهٔ زمانی نمایش مهلت‌ها</h3><p className="page-sub">این تنظیم روی این صفحه و مهلت شورش اثر دارد؛ ذخیره‌سازی و محاسبات UTC و گزارش‌های صریحِ تهران تغییر نمی‌کنند.</p><label className="f">منطقهٔ زمانی</label><select value={zone} onChange={e=>setZone(e.target.value)}>{['Asia/Tehran','UTC','Europe/London','Europe/Berlin','Asia/Dubai','America/New_York'].map(x=><option key={x}>{x}</option>)}</select><button className="btn" disabled={busy} onClick={()=>action(()=>api.adminTimeDisplay(zone))}>ذخیرهٔ منطقهٔ نمایش</button></section>
    <section className="card"><h3>تقویم فصل بازی</h3><p>روز {data.calendar.day.toLocaleString('fa-IR')} از {data.calendar.season_length.toLocaleString('fa-IR')} · آغاز داخلی: <span dir="ltr">{data.season_started_at||'تعیین نشده'}</span></p><p className="page-sub">اصلاح روز فصل، روز و فصل نقشه را تغییر می‌دهد؛ لشکرها، تولیدهای گذشته و مهلت‌های موجود جابه‌جا نمی‌شوند.</p><label className="f">روز فصل (۱ تا ۳۰)</label><input type="number" min="1" max="30" value={day} onChange={e=>setDay(Number(e.target.value))}/><label className="f">دلیل اصلاح</label><input value={reason} onChange={e=>setReason(e.target.value)}/><button className="btn" disabled={busy||reason.trim().length<3} onClick={()=>{if(confirm('روز تقویم فصل اصلاح شود؟'))action(()=>api.adminTimeSeason(day,reason))}}>اصلاح روز فصل</button></section>
    <section className="card"><h3>مهلت‌ها و رخدادهای فعال</h3><select value={kind} onChange={e=>{setKind(e.target.value);setPage(1);setSelected(null)}}>{data.sources.map(x=><option value={x.key} key={x.key}>{x.name}</option>)}</select><p className="page-sub">تاریخ آیندهٔ ساعت بازی تخمینی است و با توقف بعدی تغییر می‌کند. اگر بازی متوقف باشد، زمان باقی‌مانده ثابت است. زمان رسیدگی ممکن است کمی بعد از مهلت باشد.</p>
      {!rows?<div className="loading">در حال دریافت…</div>:<>{rows.rows.map(x=><div className="control-sub" key={x.id+x.field}><b>{x.name} {x.location} · {FIELDS[x.field]||x.field}</b><p>{stamp(x.display_at)} {x.estimated?'(پس از ادامهٔ بازی؛ تخمینی)':''}</p><small>{x.clock==='real'?'ساعت واقعی':'ساعت بازی'} · {x.remaining_seconds>0?`${Math.ceil(x.remaining_seconds/60).toLocaleString('fa-IR')} دقیقه باقی‌مانده`:'مهلت گذشته'} · {STATUSES[x.status]||x.status}</small><details><summary>زمان ذخیره‌شده</summary><span dir="ltr">{x.internal_at}</span></details>{x.editable&&<button className="btn ghost" disabled={busy} onClick={()=>{setSelected(x);setReason('')}}>اصلاح فرصت رول</button>}</div>)}{!rows.rows.length&&<p>مهلت فعالی در این صفحه نیست.</p>}<div className="grid2"><button className="btn ghost" disabled={page===1} onClick={()=>setPage(page-1)}>قبلی</button><button className="btn ghost" disabled={page*25>=rows.total} onClick={()=>setPage(page+1)}>بعدی</button></div></>}
      {selected&&<div className="control-sub"><b>اصلاح مهلت {selected.name}</b><label className="f">فرصت تازه از زمان فعلی بازی، به دقیقه</label><input type="number" min="1" max="43200" value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/><label className="f">دلیل اصلاح</label><input value={reason} onChange={e=>setReason(e.target.value)}/><button className="btn" disabled={busy||reason.trim().length<3||minutes<1} onClick={()=>{if(confirm('این بازیکن فرصت تازهٔ ارسال رول دریافت کند؟'))action(async()=>{await api.adminTimeRebellion(selected.id,minutes,selected.internal_at,reason);setSelected(null)})}}>ثبت فرصت تازه</button></div>}
    </section>
    <section className="card"><h3>چرخه‌های خودکار سرور</h3><p className="page-sub">عدد کمتر، بررسی سریع‌تر و فشار بیشتر روی سرور ایجاد می‌کند. این تنظیم مدت سفر یا فرصت رول را تغییر نمی‌دهد؛ از نوبت بعدی بررسی اعمال می‌شود.</p>{[['arrival_poll_seconds','بررسی رخدادها، ثانیه',10,300],['project_poll_seconds','بررسی پروژه، ثانیه',5,300],['market_poll_seconds','بررسی بازار، ثانیه',60,3600],['deadline_warning_hours','هشدار پیش از مهلت، ساعت',0,168]].map(([key,label,min,max])=><label className="f" key={key}>{label}<input type="number" min={min} max={max} value={workers?.[key]??0} onChange={e=>setWorkers({...workers,[key]:Number(e.target.value)})}/></label>)}<button className="btn" disabled={busy} onClick={()=>action(()=>api.adminTimeWorkers(workers))}>ذخیرهٔ چرخه‌های رسیدگی</button></section><section className="card"><h3>مدت‌ها و چرخه‌های رسیدگی</h3>{data.durations.map(x=><div className="control-sub" key={x.name}><b>{x.name}</b><p>{Number(x.value).toLocaleString('fa-IR')} {x.unit} · {x.edit}</p></div>)}<h3>تنظیم مدت‌ها</h3><p>مدت‌های پایهٔ حرکت، ساخت، جاسوسی، کول‌داون و رول در بخش «قوانین و نرخ‌ها» قرار دارند. تغییر مدت پایه، مهلت ثبت‌شدهٔ قبلی را بازنویسی نمی‌کند. انتقال فوری لشکر در بخش منابع و لشکرها انجام می‌شود؛ تغییر تنها یک تاریخ رسیدن می‌تواند مسیر حرکت را ناسازگار کند.</p></section>
  </>;
}
