import {useEffect,useRef,useState} from 'react';
import {api} from '../api.js';
export default function AdminMapManagement({toast}){
 const frame=useRef(null),current=useRef(null),[data,setData]=useState(null),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[ready,setReady]=useState(false),[error,setError]=useState('');
 const send=(d)=>frame.current?.contentWindow?.postMessage({type:'valyria-map-editor-load',placements:d.draft.placements,climate:d.draft.climate,day:d.calendar.day,gameCastles:d.gameCastles||[]},location.origin);
 async function load(){try{setError('');let [d,map]=await Promise.all([api.adminMapLayout(),api.map()]);d.gameCastles=(map.regions||[]).flatMap(r=>r.castles.map(c=>({...c,region:r.id})));if(!d.draft){const rows=await fetch('/westeros/hybrid-v2/review-data.json').then(r=>r.json());d={...d,draft:d.published||{placements:rows,climate:{mode:'auto',spring_rain:.35,autumn_rain:.65,winter_snow:.55}}}}setData(d);setDirty(false)}catch(e){setError(e.message)}}
 current.current=data;
 useEffect(()=>{load()},[]);
 useEffect(()=>{const handler=e=>{if(e.origin!==location.origin||e.source!==frame.current?.contentWindow)return;if(e.data?.type==='valyria-map-editor-ready'){setReady(true);if(current.current)send(current.current)}if(e.data?.type==='valyria-map-editor-change'){setData(d=>({...d,draft:{...d.draft,placements:e.data.placements}}));setDirty(true)}};window.addEventListener('message',handler);return()=>window.removeEventListener('message',handler)},[]);
 useEffect(()=>{if(ready&&data)send(data)},[ready,!!data]);
 useEffect(()=>{if(ready&&data)frame.current?.contentWindow?.postMessage({type:'valyria-map-editor-climate',day:data.calendar.day,climate:data.draft.climate},location.origin)},[data?.draft.climate]);
 async function action(kind){setBusy(true);try{let d=current.current;const gameCastles=d.gameCastles;if(kind==='save'||dirty){d={...await api.adminSaveMapLayout({revision:d.revision,...d.draft}),gameCastles};setData(d);setDirty(false)}if(kind!=='save'){d={...await api.adminMapLayoutAction(kind,d.revision),gameCastles};setData(d);if(kind==='rollback'&&d.published){d={...d,draft:d.published};setData(d);setDirty(true);send(d)}}toast(kind==='publish'?'نقشه برای همه منتشر شد':kind==='rollback'?'نسخهٔ قبلی فعال شد':'پیش‌نویس روی سرور ذخیره شد')}catch(e){toast(e.message)}finally{setBusy(false)}}
 const climate=(key,value)=>{setData(d=>({...d,draft:{...d.draft,climate:{...d.draft.climate,[key]:value}}}));setDirty(true)};
 if(!data)return <div className="card">{error||'در حال دریافت نقشه…'}{error&&<button className="btn" onClick={load}>دوباره بارگذاری کن</button>}</div>;
 return <><div className="card"><b>مدیریت نقشه</b><p className="page-sub">روز {data.calendar.day.toLocaleString('fa-IR')} از تقویم بازی · تغییرات ابتدا پیش‌نویس‌اند. حذف مدل از نقشه، قلعه یا مالکیتش را از بازی حذف نمی‌کند.</p><div className="grid2"><button className="btn ghost" disabled={busy} onClick={()=>action('save')}>ذخیرهٔ پیش‌نویس{dirty?' *':''}</button><button className="btn" disabled={busy} onClick={()=>action('publish')}>انتشار روی نقشهٔ بازی</button><button className="btn ghost" disabled={busy||!data.has_previous} onClick={()=>action('rollback')}>برگشت به نسخهٔ قبلی</button><button className="btn ghost" disabled={busy} onClick={()=>{if(!dirty||confirm('تغییرات ذخیره‌نشده کنار گذاشته شوند؟'))load().then(()=>{setReady(false);frame.current.src=frame.current.src})}}>بارگذاری دوباره</button></div></div>
 <iframe ref={frame} src="/westeros/hybrid-v2/index-managed.html?editor=1" title="ویرایش نقشه" style={{width:'100%',height:'75vh',minHeight:600,border:'1px solid var(--line)',borderRadius:12}}/>
 <div className="card"><b>فصل و بارش</b><label className="f">فصل<select value={data.draft.climate.mode||'auto'} onChange={e=>climate('mode',e.target.value)}><option value="auto">خودکار طبق تقویم بازی</option><option value="manual">انتخاب دستی</option></select></label>{data.draft.climate.mode==='manual'&&<select value={data.draft.climate.season||0} onChange={e=>climate('season',Number(e.target.value))}>{['بهار','تابستان','پاییز','زمستان'].map((s,i)=><option key={i} value={i}>{s}</option>)}</select>}{[['spring_rain','احتمال باران بهار',.35],['autumn_rain','احتمال باران پاییز',.65],['winter_snow','احتمال برف زمستان',.55]].map(([key,name,fallback])=><label className="f" key={key}>{name} (%)<input type="number" min="0" max="100" value={Math.round((data.draft.climate[key]??fallback)*100)} onChange={e=>climate(key,Math.max(0,Math.min(100,Number(e.target.value)))/100)}/></label>)}<p className="page-sub">بارش تصادفی با فاصله‌های هوای صاف است؛ تابستان بارش ندارد. تنظیمات پس از انتشار برای همه فعال می‌شوند.</p></div></>;
}
