import {useEffect,useState} from 'react';
import {api} from '../api.js';
import {useGame} from '../store.jsx';
export default function CharacterProfile(){
 const {toast,setMe}=useGame(),[data,setData]=useState(null),[draft,setDraft]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const load=()=>api.characterProfile().then(d=>{setData(d);setDraft(d.request?.status==='pending'?d.request.proposed:d.current);setError('')}).catch(e=>setError(e.message));
 useEffect(()=>{load()},[]);
 async function image(file,key){if(!file)return;if(file.size>256*1024){toast('حجم هر تصویر باید حداکثر ۲۵۶ کیلوبایت باشد');return}if(!['image/jpeg','image/png','image/webp'].includes(file.type)){toast('تصویر PNG، JPG یا WebP انتخاب کن');return}const reader=new FileReader();reader.onload=()=>setDraft(p=>({...p,[key]:reader.result}));reader.onerror=()=>toast('فایل خوانده نشد');reader.readAsDataURL(file)}
 async function submit(){setBusy(true);try{const payload={name:draft.name.trim(),backstory:draft.backstory.trim()};for(const k of ['profile_image','flag_image'])if(draft[k]!==data.current[k])payload[k]=draft[k]||null;const request=await api.submitCharacterProfile(payload);setData(d=>({...d,request}));toast('درخواست ویرایش کاراکتر ثبت شد')}catch(e){toast(e.message)}finally{setBusy(false)}}
 if(!draft)return <div className="card">{error||'در حال دریافت کاراکتر…'}{error&&<button className="btn" onClick={load}>تلاش دوباره</button>}</div>;
 return <><div className="sect">ساخت و ویرایش کاراکتر</div><div className="card"><p className="page-sub">نام، چهره، داستان و پرچم کاراکترت را ثبت کن. تغییرات پس از تأیید منتشر می‌شوند. اگر درخواست تازه‌ای بفرستی، همان درخواست بررسی خواهد شد.</p>{data.request&&<div className="notice-guide"><strong>{{pending:'در انتظار تأیید',approved:'آخرین درخواست تأیید شده',rejected:'آخرین درخواست رد شده',stale:'کاراکتر تغییر کرده؛ دوباره درخواست بده',processing:'در حال بررسی'}[data.request.status]}</strong>{data.request.reason&&<span>{data.request.reason}</span>}</div>}<label className="f">نام کاراکتر<input maxLength={40} value={draft.name||''} onChange={e=>setDraft(p=>({...p,name:e.target.value}))}/></label><label className="f">بک‌استوری (۴۰ تا ۲۰۰۰ نویسه)<textarea rows={7} maxLength={2000} value={draft.backstory||''} onChange={e=>setDraft(p=>({...p,backstory:e.target.value}))}/></label>{[['profile_image','عکس کاراکتر'],['flag_image','پرچم شخصی']].map(([key,label])=><div key={key}><label className="f">{label} · حداکثر ۲۵۶ کیلوبایت<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{image(e.target.files?.[0],key);e.target.value=''}}/></label>{draft[key]&&<><img src={draft[key]} alt={label} style={{width:120,height:120,objectFit:'contain',background:'#29251e',borderRadius:8}}/><button className="btn ghost" onClick={()=>setDraft(p=>({...p,[key]:null}))}>حذف {label}</button></>}</div>)}<p className="page-sub">پرچمت بر فراز قلعه‌های خاندان و روی نشان آن‌ها در نقشه قرار می‌گیرد. رنگ حاشیه، اقلیم قلعه را نشان می‌دهد.</p><button className="btn" disabled={busy||!draft.name?.trim()||draft.backstory?.trim().length<40} onClick={submit}>{busy?'در حال ارسال…':'ارسال درخواست'}</button><button className="btn ghost" style={{marginTop:8}} onClick={()=>{load();api.me().then(setMe).catch(()=>{})}}>بررسی وضعیت درخواست</button></div></>;
}
